from setuptools import setup

setup(name='czitools',
      version='0.0.1',
      description='Read and analyze CZI (and OME-TIFF) files',
      long_description='Collection of functions and tools to read and analyze CZI (and OME-TIFF) files',
      keywords='image analysis czi ome-tiff file read segmentation',
      url='https://github.com/sebi06/czitools',
      author='Sebastian Rhode',
      author_email='sebrhode@gmail.com',
      license='BSD 3-Clause License',
      packages=['czitools'],
      python_requires='>=3.7',

      classifiers=[
          'Development Status :: 3 - Alpha',
          'Intended Audience :: Science/Research',
          'Topic :: Scientific/Engineering',
          'License :: OSI Approved :: BSD License',
          'Programming Language :: Python :: 3.7',
      ],

      install_requires=[
          'numpy>=1.18.4',
          'scikit-image>=0.17.2',
          'aicsimageio>=3.3.4',
          'aicspylibczi>=2.8.0',
          'czifile>=2019.7.2',
          'xmltodict>=0.12.0',
          'pandas>=1.1.4',
          'seaborn>=0.11.0',
          'scipy>=1.5.4',
          'matplotlib>=3.3.3',
          'lxml>=4.5.0',
          'openpyxl>=3.0.3',
          'progressbar2>=3.51.3',
          'MightyMosaic>=1.2.3',
          'napari>=0.4.4',
          'napari-aicsimageio>=0.2.0',
          'apeer-ometiff-library>=1.7.2',
          # 'csbdeep>=0.6.0',
          # 'stardist',
          'nptyoing>=1.3.0',
          'pydash>=4.8.0',
      ],
      include_package_data=True,
      zip_safe=False)
