from setuptools import setup

setup(name='czitools',
      version='0.0.1',
      description='Read and analyze CZI (and OME-TIFF) files',
      long_description='Collection of functions and tool to read and analyze CZI (and OME-TIFF) files',
      keywords='image analysis czi ome-tiff file read segmentation',
      url='https://github.com/sebi06/czitools',
      author='Sebastian Rhode',
      author_email='sebastian.rhode@zeiss.com',
      license='BSD 3-Clause License',
      packages=['czitools'],
      python_requires='>=3.7',

      classifiers=[
          'Development Status :: 3 - Alpha',
          'Intended Audience :: Science/Research',
          'Topic :: Scientific/Engineering',
          'License :: OSI Approved :: BSD License',
          'Programming Language :: Python :: 3.7',
      ],

      install_requires=[
          'numpy>=1.18.4',
          'scikit-image>=0.16.2',
          'aicsimageio>=3.2.3',
          'aicspylibczi>=2.6.0',
          'czifile>=2019.7.2',
          'xmltodict>=0.12.0',
          'pandas>=1.0.3',
          'seaborn>=0.10.1',
          'scikit-image>=0.16.2',
          'scipy>=1.4.1',
          'matplotlib>=3.2.1',
          'lxml>=4.5.0',
          'openpyxl>=3.0.3',
          'progressbar2>=3.51.3',
          'MightyMosaic>=1.2.3',
          'napari>=0.3.5',
          'napari-aicsimageio>=0.1.3',
          'apeer-ometiff-library>=1.6.0',
          'csbdeep>=0.5.1',
          'ipywidgets>=7.5.1',
          'pydash>=4.8.0',
      ],
      include_package_data=True,
      zip_safe=False)
